---
# tasks file for ansible-ark-survival
- name: Ensure Ark Survival user group exists
  ansible.builtin.group:
    name: "{{ ark_survival_group }}"
    state: present

- name: Ensure Ark Survival user exists
  ansible.builtin.user:
    name: "{{ ark_survival_name }}"
    group: "{{ ark_survival_group }}"
    shell: /usr/sbin/nologin
    create_home: true
    home: "/home/{{ ark_survival_name }}"
    state: present

- name: Install SteamCMD and Ark server
  ansible.builtin.include_tasks: steamcmd.yml

- name: Ensure Ark server directory exists with correct permissions
  ansible.builtin.file:
    path: "/home/{{ ark_survival_name }}/ark"
    state: directory
    owner: "{{ ark_survival_name }}"
    group: "{{ ark_survival_group }}"
    mode: "0755"
    recurse: true

- name: Ensure game user settings file is present
  ansible.builtin.copy:
    src: GameUserSettings.ini
    dest: "/home/{{ ark_survival_name }}/ark/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini"
    owner: "{{ ark_survival_name }}"
    group: "{{ ark_survival_group }}"
    mode: "0644"
  notify: Restart ark service

- name: Ensure Ark service file is present
  ansible.builtin.template:
    src: ark.service.j2
    dest: /etc/systemd/system/ark.service
    mode: "0644"
  notify: Restart ark service

- name: Enable and start ark service
  ansible.builtin.systemd:
    name: ark
    enabled: true
    state: started
